# Generated by Django 6.0.3 on 2026-04-21 03:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('due_determiner', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPoints', models.IntegerField(default=0)),
                ('currentWinStreak', models.IntegerField(default=0)),
                ('currentLoseStreak', models.IntegerField(default=0)),
                ('lucids', models.JSONField(default=list)),
                ('password_last_changed', models.DateTimeField(default=django.utils.timezone.now)),
                ('alarm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.alarm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lucid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField()),
                ('nickname', models.CharField(blank=True, max_length=64)),
                ('species_id', models.IntegerField()),
                ('level', models.PositiveIntegerField(default=1)),
                ('upgrade_history', models.JSONField(blank=True, default=list)),
                ('pending_levelups', models.PositiveIntegerField(default=0)),
                ('party_slot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lucids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('party_slot', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('party_slot__isnull', True), ('party_slot__in', [1, 2, 3]), _connector='OR'), name='lucid_valid_party_slot'), models.UniqueConstraint(condition=models.Q(('party_slot__isnull', False)), fields=('owner', 'party_slot'), name='lucid_unique_party_slot_per_owner')],
            },
        ),
    ]
