# Generated by Django 6.0.3 on 2026-04-18 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lucid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('types', models.JSONField(default=list)),
                ('description', models.CharField(max_length=1024)),
                ('spawn_rate', models.FloatField()),
                ('spawn_level_offset', models.IntegerField()),
                ('evolution', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('due_determiner', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPoints', models.IntegerField(default=0)),
                ('currentWinStreak', models.IntegerField(default=0)),
                ('currentLoseStreak', models.IntegerField(default=0)),
                ('lucids', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
