# Generated by Django 6.0.3 on 2026-03-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='wake_up_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
