# Generated by Django 6.0.3 on 2026-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alarm_wake_up_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='due_determiner',
            field=models.BooleanField(default=False),
        ),
    ]
