# Generated by Django 6.0.3 on 2026-04-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alarm_due_determiner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='wake_up_time',
        ),
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
